// screen types
export const CHANGE_SCREEN = 'CHANGE_SCREEN'
export const CHANGE_NOTIFICATION = 'CHANGE_NOTIFICATION'
export const CHANGE_BOTTOM_VALUE = 'CHANGE_BOTTOM_VALUE'
export const CHANGE_LOCAL_NOTIFICATION = 'CHANGE_LOCAL_NOTIFICATION'
export const CHANGE_LOCAL_TEXT = 'CHANGE_LOCAL_TEXT'
export const CHANGE_LOCAL_STATUS = 'CHANGE_LOCAL_STATUS'

// user types
export const CHANGE_USER_ID = 'CHANGE_USER_ID'
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const CHANGE_USER_PHONE = 'CHANGE_USER_PHONE'
export const CHANGE_USER_CITY = 'CHANGE_USER_CITY'
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL'
export const CHANGE_NAME_ORG = 'CHANGE_NAME_ORG'
export const CHANGE_NAME_SALON = 'CHANGE_NAME_SALON'
export const CHANGE_INN_ORG = 'CHANGE_INN_ORG'
export const CHANGE_SUBSCRIBE = 'CHANGE_SUBSCRIBE'
export const CHANGE_TUTORIAL = 'CHANGE_TUTORIAL'

export const CHANGE_USER_ALL = 'CHANGE_USER_ALL'
export const CHANGE_TOKEN = 'CHANGE_TOKEN'
export const SET_USER = 'SET_USER'

// notation data
export const CHANGE_NOTATION_COUNT_WORKER = 'CHANGE_NOTATION_COUNT_WORKER'
export const CHANGE_NOTATION_INTERVAL = 'CHANGE_NOTATION_INTERVAL'
export const CHANGE_NOTATION_SORT = 'CHANGE_NOTATION_SORT'
export const CHANGE_NOTATION_LIST_SPECIALISTS =
  'CHANGE_NOTATION_LIST_SPECIALISTS'
export const CHANGE_NOTATION_LIST_MASTERS = 'CHANGE_NOTATION_LIST_MASTERS'
export const CHANGE_NOTATION_DATE = 'CHANGE_NOTATION_DATE'
export const CHANGE_SORTED_MASTERS = 'CHANGE_SORTED_MASTERS'

// filter
export const CHANGE_CHARTJOB = 'CHANGE_CHARTJOB'

// services

export const CHANGE_SERVICES = 'CHANGE_SERVICES'
export const ADD_SERVICE = 'ADD_SERVICE'
export const DELETE_SERVICE = 'DELET_SERVICE'

// filial
export const CHANGE_FILIAL_ID = 'CHANGE_FILIAL_ID'
export const CHANGE_FILIAL_NAME = 'CHANGE_FILIAL_NAME'
export const CHANGE_FILIAL_MASTERS = 'CHANGE_FILIAL_MASTERS'
export const UPDATE_FILIAL_MASTER = 'UPDATE_FILIAL_MASTER'
export const CHANGE_FILIAL_SERVICE_PROPS = 'CHANGE_FILIAL_SERICE_PROPS'
export const CHANGE_FILIAL_SERVICE_DATA = 'CHANGE_FILIAL_SERVICE_DATA'
export const SET_FILIAL = 'SET_FILIAL'

export const CHANGE_TEMP = 'CHANGE_TEMP'

// note
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const SET_NOTE = 'SET_NOTE'

// createNotation
export const CHANGE_CREATENOTATION_CLIENT_ID = 'CHANGE_CREATENOTATION_CLIENT_ID'
export const CHANGE_CREATENOTATION_SPECIALIST_ID =
  'CHANGE_CREATENOTATION_SPECIALIST_ID'
export const CHANGE_CREATENOTATION_SERVICES = 'CHANGE_CREATENOTATION_SERVICES'
export const CHANGE_CREATENOTATION_SUBSERVICE_ID =
  'CHANGE_CREATENOTATION_SUBSERVICE_ID'

// clients

export const SET_CLIENTS = 'SET_CLIENTS'

// masters

export const SET_MASTERS = 'SET_MASTERS'

// loyalty

export const SET_BONUS_CARDS = 'SET_BONUS_CARDS'
export const SET_CERTIFICATES = 'SET_SERTIFICATES'
export const CALCULATE_BONUS_LENGTH = 'CALCULATE_BONUS_LENGTH'
export const CALCULATE_CERTIFICATE_LENGTH = 'CALCULATE_CERTIFICATE_LENGTH'
