import {StyleSheet} from 'react-native'

export const colors = {
  lightGreen: '#00AE6C',
  darkGreen: '#018050',
  secondaryGreen: '#E6F3EE',
  white: '#FFF',
  black: '#333333',
  gray: '#F7F7F7',
  bluishGray: '#E8EDEF',
  secondaryGray: '#BDBDBD',
  lines: '#EAEAEA',
  background: '#F2F2F7',
  red: '#EB5757',
}

export const Style = StyleSheet.create({
  textInput: {
    height: 56,
    marginTop: 16,
    marginLeft: 24,
    marginRight: 24,
    paddingLeft: 19,
    borderRadius: 16,
    borderWidth: 2,
    backgroundColor: '#EFF0F6',
    borderColor: '#EFF0F6',
  },
  textInputFocused: {
    height: 56,
    marginTop: 16,
    marginLeft: 24,
    marginRight: 24,
    paddingLeft: 19,
    borderRadius: 16,
    borderWidth: 2,
    backgroundColor: '#FFFFFF',
    borderColor: colors.darkGreen,
  },
  main: {
    flex: 1,
    padding: 20,
    paddingTop: 60,
  },
  button: {
    backgroundColor: colors.darkGreen,
    borderRadius: 16,
    height: 56,
    marginLeft: 16,
    marginRight: 16,
  },
  buttonTitle: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '700',
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'column',
  },
  buttonInput: {
    height: 56,
    marginTop: 16,
    marginLeft: 24,
    marginRight: 24,
    paddingLeft: 19,
    borderRadius: 16,
    borderWidth: 2,
    backgroundColor: '#EFF0F6',
    borderColor: '#EFF0F6',
    justifyContent: 'center',
  },
  linkBlock: {
    borderTopWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.gray,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 54,
    paddingVertical: 16,
    marginLeft: 16,
    marginRight: 16,
  },
  modal: {
    flex: 1,
    backgroundColor: colors.white,
  },
  modalContainer: {
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    marginLeft: 16,
    backgroundColor: colors.gray,
    marginRight: 16,
  },
  screenContainer: {
    backgroundColor: colors.white,
    marginLeft: 16,
    marginRight: 16,
  },
  modalHeader: {
    height: 56,
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    alignItems: 'center',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  modalHeaderGray: {
    height: 56,
    backgroundColor: colors.gray,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    alignItems: 'center',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomWidth: 1,
    borderStyle: 'solid',
    borderBottomColor: colors.lines,
  },
  screenHeader: {
    backgroundColor: colors.white,
    height: 44,
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
  },
})
